# Based on https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# Removed docker image caching for the sake of simplicity.

version: 2.1

# Dynamic config needs to be enabled in the Project Settings for this to take effect
# https://circleci.com/docs/dynamic-config/
setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            .circleci/generate-config.sh > .circleci/config-generated.yml
      - continuation/continue:
          configuration_path: .circleci/config-generated.yml

workflows:
  setup:
    jobs:
      - setup