version: 2
jobs:
  build:
    working_directory: ~/rails_template
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run: sudo apt update && sudo apt install postgresql-client
      - restore_cache:
          keys:
            - rails_template-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
      - run: gem install bundler -v '2.2.14'
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: rails_template-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Install NPM Dependencies via Yarn
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: rails_template-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: '~/rails_template'
          paths: '*'

  rubocop:
    working_directory: ~/rails_template
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      - attach_workspace:
          at: '~/rails_template'
      - run: gem install bundler -v '2.2.14'
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: rails_template-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Run rubocop
          command: bundle exec rubocop

  test:
    working_directory: ~/rails_template
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          RAILS_ENV: test
      - image: postgres:10.6-alpine
        environment:
          POSTGRES_USER: rails_template_user
          POSTGRES_DB: test_db
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - attach_workspace:
          at: '~/rails_template'

      - run: gem install bundler -v '2.2.14'
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: rails_template-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run: bundle exec rake db:migrate RAILS_ENV=test
      - run:
          name: Run Rspec
          command: bundle exec rspec

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build
