# Based on https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/

version: 2
jobs:
  build:
    working_directory: /rails-template
    docker:
      # From https://registry.hub.docker.com/_/docker/tags
      - image: docker:20.10.21-git
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Install dependencies
      #     command: |
      #       apk add --no-cache \
      #         py-pip=9.0.0-r1
      #       pip install \
      #         docker-compose==1.12.0 \
      #         awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/rails-template.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/rails-template.tar | true
      - run:
          name: Run test
          command: |
            ./test-docker.sh
      - run:
          name: Save Docker image layer cache
          # Needs to match image tag in test-docker.sh:
          command: |
            mkdir -p /caches
            docker save -o /caches/rails-template.tar rails-template
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/rails-template.tar
